on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Debug Inputs (Bypass Masking)
        run: |
          echo "DOCKERHUB_USERNAME (Base64 Encoded):"
          echo -n "${{ secrets.DOCKERHUB_USERNAME }}" | base64

          echo "DOCKERHUB_REPO (Base64 Encoded):"
          echo -n "${{ secrets.DOCKERHUB_REPO }}" | base64

          echo "DOCKERHUB_TOKEN (Base64 Encoded - First 10 Characters Only):"
          echo -n "${{ secrets.DOCKERHUB_TOKEN }}" | base64 | cut -c1-10


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: |
          VERSION=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: ./.github/actions/docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_repo: ${{ secrets.DOCKERHUB_REPO }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile.backend

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Test Python
        uses: ./.github/actions/test-python
        with:
          docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ needs.build.outputs.version }}
